# Generated by Django 4.0.4 on 2022-05-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='matricule',
            field=models.IntegerField(default=0),
        ),
    ]
