# Generated by Django 4.0.4 on 2022-05-24 23:03

import Personnel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=255)),
                ('specialite', models.CharField(max_length=200)),
                ('matricule', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OffreLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('specialite', models.CharField(choices=[('Informatique', 'Informatique'), ('SCIENCES HUMAINES', 'SCIENCES HUMAINES'), ('SCIENCES SOCIALES', 'SCIENCES SOCIALES'), ('SCIENCES ECONOMIQUES ', 'SCIENCES ECONOMIQUES ')], default='Informatique', max_length=200)),
                ('fichier', models.FileField(blank=True, upload_to='fileOffreLicence', validators=[Personnel.models.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='OffreMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('specialite', models.CharField(choices=[('Informatique', 'Informatique'), ('SCIENCES HUMAINES', 'SCIENCES HUMAINES'), ('SCIENCES SOCIALES', 'SCIENCES SOCIALES'), ('SCIENCES ECONOMIQUES ', 'SCIENCES ECONOMIQUES ')], default='Informatique', max_length=200)),
                ('fichier', models.FileField(blank=True, upload_to='fileOffreMaster', validators=[Personnel.models.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Personnel.users',),
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='annee',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(default='NTIC', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='filier',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='is_etudiant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_personnel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='matricule',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='moyenne_s1',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='moyenne_s2',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='moyenne_s3',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='moyenne_s4',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='moyenne_s5',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='moyenne_s6',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='specialite',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('SCIENCES HUMAINES', 'SCIENCES HUMAINES'), ('SCIENCES SOCIALES', 'SCIENCES SOCIALES'), ('SCIENCES ECONOMIQUES ', 'SCIENCES ECONOMIQUES ')], default='Informatique', max_length=200),
        ),
    ]
