# Generated by Django 4.0.4 on 2022-05-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel', '0002_emailsendmodel_offrelicence_offremaster_verifieduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_personnel',
            field=models.BooleanField(default=False),
        ),
    ]
