# Generated by Django 4.0.4 on 2022-05-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel', '0003_alter_users_is_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='classment',
            field=models.FloatField(default=None, null=True),
        ),
    ]
