# Generated by Django 4.0.4 on 2022-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('matricul_bac', models.IntegerField(max_length=8)),
                ('bac_anne', models.IntegerField(max_length=4)),
                ('moyenne_bac', models.FloatField(max_length=4)),
                ('note_math', models.FloatField(max_length=4)),
                ('note_phy', models.FloatField(max_length=4)),
                ('moyenne_classment', models.FloatField(blank=True, max_length=4)),
                ('matricul_univ', models.IntegerField(blank=True, max_length=12)),
            ],
        ),
    ]
