# Generated by Django 4.0.4 on 2022-05-24 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel', '0003_alter_users_is_personnel'),
        ('Etudiant', '0002_alter_inscriptionlicense_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionLicenceSpecialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200)),
                ('matricule', models.IntegerField()),
                ('choix_1', models.CharField(max_length=10)),
                ('choix_2', models.CharField(max_length=10)),
                ('choix_3', models.CharField(max_length=10)),
                ('choix_4', models.CharField(max_length=10)),
                ('offreLicence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel.offrelicence')),
            ],
        ),
    ]
