# Generated by Django 4.0.4 on 2022-05-31 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_inscriptionlicencespecialite_and_more'),
        ('Personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionmasterspecialite',
            name='offreMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel.offremaster'),
        ),
        migrations.AddField(
            model_name='inscriptionlicencespecialite',
            name='offreLicence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel.offrelicence'),
        ),
    ]
