# Generated by Django 4.0.4 on 2022-05-25 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel', '0003_alter_users_is_personnel'),
        ('Etudiant', '0004_alter_inscriptionlicencespecialite_offrelicence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionlicencespecialite',
            name='offreLicence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel.offrelicence'),
        ),
        migrations.CreateModel(
            name='InscriptionMasterSpecialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200)),
                ('matricule', models.IntegerField()),
                ('choix_1', models.CharField(max_length=10)),
                ('choix_2', models.CharField(max_length=10)),
                ('choix_3', models.CharField(max_length=10)),
                ('choix_4', models.CharField(max_length=10)),
                ('offreMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel.offremaster')),
            ],
        ),
    ]
