# Generated by Django 4.0.4 on 2022-05-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0005_alter_inscriptionlicencespecialite_offrelicence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionlicense',
            name='note_math',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionlicense',
            name='note_phy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
