# Generated by Django 4.0.4 on 2022-05-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0006_alter_inscriptionlicense_note_math_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionlicense',
            name='moyenne_classment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
